---

#ansible-playbook -i localhost, update_poap.yml -e "poap_script=./poap.py"

  - name: CREATE MD5 FILE FOR CONFIGS
    hosts: all
    gather_facts: no
    connection: local

    vars:
      base_path: "/srv/ftp/conf"

    tasks:

      - name: SET CONFIG FILE FROM SERIAL
        set_fact: 
          config_file: "conf_{{ device_to_serial_mapping[device] }}.cfg"

      - name: STAT FILE FOR MD5 HASH
        stat:
          path: "{{ base_path }}/{{ config_file }}"
        register: "md5_check"

      - name: SET MD5 FROM STAT
        set_fact: 
          md5sum: "{{ md5_check.stat.md5 }}"

      - name: SHOW MD5 SUM
        debug:
          var: "md5sum"

      - name: BUILD MD5 FILE
        template:
          src: "templates/md5.j2"
          dest: "{{ base_path }}/{{ config_file }}.md5"

