---

    # ensure snmp community is configured
    - nxos_config:
        lines: "snmp-server community {{ item.community }} group {{ item.group }}"
        provider: "{{ nxos_provider }}"
      with_items: "{{ snmp }}"

